- name: add apache user to nagios group
  sudo: true
  user: >
    groups=nagios
    name=apache

- name: copy nagios vhost
  sudo: true
  template: >
    src=nagios.vhost.j2
    dest=/etc/apache2/sites-available/nagios.conf
    owner=root
    group=root
    mode=640

- name: enable nagios vhost
  sudo: true
  command: "a2ensite nagios"

- name: disable default vhost
  sudo: true
  command: "a2dissite 000-default"

- name: enable apache cgi
  sudo: true
  command: "a2enmod cgi"
