- name: add apache user to nagios group
  sudo: true
  user: >
    groups=nagios
    name=apache

- name: add passwords for nagios
  sudo: true
  htpasswd: >
    name="{{nagios_admin_user}}"
    password="{{nagios_admin_password}}"
    path=/usr/local/nagios/etc/htpasswd.users

- name: set permissions on new password file
  sudo: true
  file: >
    path=/usr/local/nagios/etc/htpasswd.users
    owner=nagios
    group=nagcmd

- name: copy nagios vhost
  sudo: true
  template: >
    src=nagios.vhost.j2
    dest=/etc/apache2/sites-available/nagios.conf
    owner=root
    group=root
    mode=640
  when: not (legacy | default(false))

- name: copy nagios vhost for pre-trusty
  sudo: true
  template: >
    src=nagios.vhost.j2
    dest=/etc/apache2/sites-available/nagios
    owner=root
    group=root
    mode=640
  when: legacy | default(false)

- name: enable nagios vhost
  sudo: true
  command: "a2ensite nagios"

- name: enable apache ssl
  sudo: true
  command: "a2enmod ssl"

- name: enable apache ssl
  sudo: true
  command: "a2enmod cgi"
