# Install binaries
- name: install binaries for clients
  sudo: true
  apt: deb={{ downloadpath | mandatory  }}/{{ item }} state=present dpkg_options=force-overwrite
  with_items:
    binary_nagios_plugins_packages
