# Create nagios users and groups.
- name: create nagios group
  sudo: true
  group: >
    name={{ nagios_group }}

- name: create nagcmd group
  sudo: true
  group: >
    name={{ nagcmd_group }}

- name: create nagios user
  sudo: true
  user: >
    group={{ nagios_user_group }}
    groups={{ nagios_user_groups }}
    name={{ nagios_user }}
    home=/usr/local/{{ nagios_user }}
    comment="Nagios Admin"
