# Setup nagios user and group
- tasks:
  include: setup-users-groups.yml

- name: add user www-data to nagcmd group
  sudo: True
  user: >
    groups=nagcmd
    name=www-data

# Check if nagios is already installed
- name: Check if nagios is already installed
  stat: path="/usr/local/nagios/etc/nagios.cfg"
  register: nagioscfg

# Install needed nagios packages for build nagios from source
- tasks:
  include: install-nagios-packages.yml
  when: not nagioscfg.stat.exists

# build and install nagios.
- tasks:
  include: build-nagios.yml
  when: not nagioscfg.stat.exists

# Build and install nagios check plugins.
- tasks:
  include: build-plugins.yml
  when: build_nagios_plugins

# Build and install nagios remote checks.
- tasks:
  include: build-nrpe.yml
  when: build_nagios_nrpe

# Setup apache.
- tasks:
  include: apache.yml

# Create nagios tmp folder
- tasks:
  include: create-nagios-temp-folder.yml

# download binaries for server
- tasks:
  include: download-binaries-server.yml

# Install binaries for server
- tasks:
  include: install-binaries-server.yml

# download binaries for clients
- tasks:
  include: download-binaries-client.yml

# Install binaries for clients
- tasks:
  include: install-binaries-client.yml

# Setup pagerduty.
- tasks:
  include: pagerduty.yml
  when: nagios_enable_pagerduty_notifications

# Setup SES for notifications.
- tasks:
  include: ses.yml
  when: nagios_enable_ses_notifications

- name: disable flap detection
  sudo: true
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="enable_flap_detection=0"
    regexp="^enable_flap_detection.*$"

- name: overwrite contacts.cfg
  sudo: true
  template: >
    src=contacts.cfg.j2
    dest=/usr/local/nagios/etc/objects/contacts.cfg
    owner=nagios
    group=nagios
    mode=640

- name: install nagios upstart script
  sudo: true
  copy: >
    src=nagios.conf
    dest=/etc/init/nagios.conf
    owner=nagios
    group=nagios
    mode=640

- name: restart nagios
  sudo: true
  service: name=nagios state=restarted
  notify: restart apache
